name = "glexer"
version = "0.4.2"
description = "A lexer for Gleam source code"
licenses = ["MIT"]

[dependencies]
gleam_stdlib = "~> 0.28"

[dev-dependencies]
gleeunit = "~> 0.10"
glychee = "~> 0.2"
simplifile = "~> 0.1"
