name = "glexer"
version = "1.0.1"
description = "A lexer for Gleam source code"
licenses = ["MIT"]
gleam = ">= 1.0.0"
repository = { type = "github", user = "DanielleMaywood", repo = "glexer" }

[dependencies]
gleam_stdlib = "~> 0.32"

[dev-dependencies]
gleeunit = "~> 1.1"
glychee = "~> 1.1"
simplifile = "~> 1.7"
