name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.2
          gleam-version: 0.32.2
          elixir-version: 1.15.0
          rebar3-version: 3
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
